# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name gtk-traymanager

Name:           ghc-%{pkg_name}
Version:        0.1.5
Release:        1%{?dist}
Summary:        A wrapper around the eggtraymanager library for Linux system trays

License:        LGPLv2+
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkg_name}-%{version}/%{pkg_name}-%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-glib-devel
BuildRequires:  ghc-gtk-devel
BuildRequires:  pkgconfig(gtk+-2.0)
BuildRequires:  pkgconfig(x11)
# End cabal-rpm deps

%description
This package provides a wrapper around the prolific eggtraymanager code.
Note that it is *NOT* itself a system tray widget, though it is a very
convenient utility for implementing one. This package adopts the style of
gtk2hs and is designed to work well with it.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Begin cabal-rpm deps:
Requires:       pkgconfig(gtk+-2.0)
Requires:       pkgconfig(x11)
# End cabal-rpm deps

%description devel
This package provides the Haskell %{pkg_name} library development
files.


%prep
%setup -q -n %{pkg_name}-%{version}


%build
%ghc_lib_build


%install
%ghc_lib_install


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%doc LICENSE


%files devel -f %{name}-devel.files
%doc README.md


%changelog
* Sat Oct 31 2015 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.1.5-1
- spec file generated by cabal-rpm-0.9.6
