# Created by pyp2rpm-2.0.0
%global pypi_name pylatest

Name:           python-%{pypi_name}
Version:        0.0.5.dev1
Release:        2%{?dist}
Summary:        Testcase description generation tools.

License:        GPLv3
URL:            https://github.com/mbukatov/%{pypi_name}
Source0:        %{pypi_name}-%{version}.tar.gz
BuildArch:      noarch
 
BuildRequires:  python2-devel
BuildRequires:  python-setuptools
 
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools

%description
Pylatest project provides a set of tools which allows you to:
* Write a description of a test case using reStructuredText syntax.
* Include this description into a python source code directly, split into
  individual sections or actions to be performed, so that the description and
  test automation code are stored next to each other.

%package -n     python2-%{pypi_name}
Summary:        Testcase description generation tools.
%{?python_provide:%python_provide python2-%{pypi_name}}
 
Requires:       python-docutils
Requires:       python-setuptools
%description -n python2-%{pypi_name}
Pylatest project provides a set of tools which allows you to:
* Write a description of a test case using reStructuredText syntax.
* Include this description into a python source code directly, split into
  individual sections or actions to be performed, so that the description and
  test automation code are stored next to each other.

%package -n     python3-%{pypi_name}
Summary:        Testcase description generation tools.
%{?python_provide:%python_provide python3-%{pypi_name}}
 
Requires:       python3-docutils
Requires:       python3-setuptools
%description -n python3-%{pypi_name}
Pylatest project provides a set of tools which allows you to:
* Write a description of a test case using reStructuredText syntax.
* Include this description into a python source code directly, split into
  individual sections or actions to be performed, so that the description and
  test automation code are stored next to each other.

%prep
%autosetup -n %{pypi_name}-%{version}
# Remove bundled egg-info
rm -rf %{pypi_name}.egg-info

%build
%py2_build
%py3_build

%install
# Must do the subpackages' install first because the scripts in /usr/bin are
# overwritten with every setup.py install.
%py3_install
cp %{buildroot}/%{_bindir}/pylatest2html %{buildroot}/%{_bindir}/pylatest2html-3
ln -sf %{_bindir}/pylatest2html-3 %{buildroot}/%{_bindir}/pylatest2html-%{python3_version}
cp %{buildroot}/%{_bindir}/pylatest2htmlplain %{buildroot}/%{_bindir}/pylatest2htmlplain-3
ln -sf %{_bindir}/pylatest2htmlplain-3 %{buildroot}/%{_bindir}/pylatest2htmlplain-%{python3_version}
cp %{buildroot}/%{_bindir}/py2pylatest %{buildroot}/%{_bindir}/py2pylatest-3
ln -sf %{_bindir}/py2pylatest-3 %{buildroot}/%{_bindir}/py2pylatest-%{python3_version}
cp %{buildroot}/%{_bindir}/pylatest-template %{buildroot}/%{_bindir}/pylatest-template-3
ln -sf %{_bindir}/pylatest-template-3 %{buildroot}/%{_bindir}/pylatest-template-%{python3_version}

%py2_install
cp %{buildroot}/%{_bindir}/pylatest2html %{buildroot}/%{_bindir}/pylatest2html-2
ln -sf %{_bindir}/pylatest2html-2 %{buildroot}/%{_bindir}/pylatest2html-%{python2_version}
cp %{buildroot}/%{_bindir}/pylatest2htmlplain %{buildroot}/%{_bindir}/pylatest2htmlplain-2
ln -sf %{_bindir}/pylatest2htmlplain-2 %{buildroot}/%{_bindir}/pylatest2htmlplain-%{python2_version}
cp %{buildroot}/%{_bindir}/py2pylatest %{buildroot}/%{_bindir}/py2pylatest-2
ln -sf %{_bindir}/py2pylatest-2 %{buildroot}/%{_bindir}/py2pylatest-%{python2_version}
cp %{buildroot}/%{_bindir}/pylatest-template %{buildroot}/%{_bindir}/pylatest-template-2
ln -sf %{_bindir}/pylatest-template-2 %{buildroot}/%{_bindir}/pylatest-template-%{python2_version}


%check
%{__python2} setup.py test
#%{__python3} setup.py test

%files -n python2-%{pypi_name} 
%doc README.rst LICENSE
%{_bindir}/pylatest2html
%{_bindir}/pylatest2html-2
%{_bindir}/pylatest2html-%{python2_version}
%{_bindir}/pylatest2htmlplain
%{_bindir}/pylatest2htmlplain-2
%{_bindir}/pylatest2htmlplain-%{python2_version}
%{_bindir}/py2pylatest
%{_bindir}/py2pylatest-2
%{_bindir}/py2pylatest-%{python2_version}
%{_bindir}/pylatest-template
%{_bindir}/pylatest-template-2
%{_bindir}/pylatest-template-%{python2_version}
%{python2_sitelib}/%{pypi_name}
%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%files -n python3-%{pypi_name} 
%doc README.rst LICENSE
%{_bindir}/pylatest2html-3
%{_bindir}/pylatest2html-%{python3_version}
%{_bindir}/pylatest2htmlplain-3
%{_bindir}/pylatest2htmlplain-%{python3_version}
%{_bindir}/py2pylatest-3
%{_bindir}/py2pylatest-%{python3_version}
%{_bindir}/pylatest-template-3
%{_bindir}/pylatest-template-%{python3_version}
%{python3_sitelib}/%{pypi_name}
%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%changelog
* Sun Feb 21 2016 Martin B. - 0.0.5.dev1-2
- Disable python3 unit tests during build.

* Sun Feb 21 2016 Martin B. - 0.0.5.dev1-1
- Initial specfile generated by py2rpm-2.0.0
