# https://fedoraproject.org/wiki/Packaging:Haskell

Name:           taffybar
Version:        0.4.5
Release:        2%{?dist}
Summary:        A desktop bar similar to xmobar, but with more GUI

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-HStringTemplate-devel
BuildRequires:  ghc-HTTP-devel
BuildRequires:  ghc-X11-devel
BuildRequires:  ghc-cairo-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-dbus-devel
BuildRequires:  ghc-dyre-devel
BuildRequires:  ghc-enclosed-exceptions-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-gtk-devel
BuildRequires:  ghc-gtk-traymanager-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-network-devel
BuildRequires:  ghc-network-uri-devel
BuildRequires:  ghc-old-locale-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-safe-devel
BuildRequires:  ghc-split-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-time-locale-compat-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-utf8-string-devel
BuildRequires:  ghc-xdg-basedir-devel
BuildRequires:  ghc-xmonad-contrib-devel
BuildRequires:  ghc-xmonad-devel
BuildRequires:  pkgconfig(gtk+-2.0)
# End cabal-rpm deps

%description
A somewhat fancier desktop bar than xmobar. This bar is based on gtk2hs and
provides several widgets (including a few graphical ones). It also sports an
optional snazzy system tray.


%prep
%setup -q


%build
%ghc_bin_build


%install
%ghc_bin_install


%files
%license LICENSE
%doc README.md CHANGELOG.md taffybar.hs.example taffybar.rc
%{_bindir}/%{name}


%changelog
* Sun Nov 01 2015 Martin Bukatovič <martin.bukatovic@gmail.com> -  0.4.5-2
- Initial package
- spec file changed to follow binary only (Bin) haskell guidelines

* Sat Oct 31 2015 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.4.5-1
- spec file generated by cabal-rpm-0.9.6
